name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check Formatting
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Run Clippy
        run: cargo clippy -- -D warnings

  test:
    name: TestSuite
    runs-on: ubuntu-latest
    env:
      APP__ENV: development
      APP__SERVER__HOST: 127.0.0.1
      APP__SERVER__PORT: 8000
      APP__DATABASE__ENGINE: postgres
      APP__DATABASE__HOST: localhost
      APP__DATABASE__PORT: 5433
      APP__DATABASE__USER: admin
      APP__DATABASE__PASSWORD: supersecret
      APP__DATABASE__NAME: gh_workflow_db
      APP__AUTH__JWT_SECRET: "s9fK8!dL2vB#4rQm7pWzX1eR6tUqH0yJ"
      APP__AUTH__JWT_ACCESS_EXPIRATION_TIME_IN_HOURS: 1
      APP__AUTH__JWT_REFRESH_EXPIRATION_TIME_IN_HOURS: 24
      APP__AUTH__JWT_ONE_TIME_PASSWORD_LIFETIME_IN_MINUTES: 5
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: supersecret
          POSTGRES_DB: gh_workflow_db
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install sqlx-cli
        run: cargo install sqlx-cli --no-default-features --features postgres
      - name: Run Migrations
        run: sqlx migrate run --database-url postgres://admin:supersecret@localhost:5433/gh_workflow_db
      - name: Run All Tests
        run: cargo test
